### ISSUE TITLE
Eliza is not compatible with PHP 7.1

### ISSUE THREAD

**Issue by PabloKowalczyk** [Crell/Eliza#2]
There is a problem with constant `PREG_UNMATCHED_AS_NULL`, it was added in PHP `7.2.0` ([docs](http://php.net/manual/en/migration72.constants.php)) but version required by `Eliza` is `7.1`, this results in following error `Use of undefined constant PREG_UNMATCHED_AS_NULL - assumed 'PREG_UNMATCHED_AS_NULL'` on PHP versions lower than `7.2`.

Possible solution is to bump required `PHP` version or not use this constant :)

**Comment by Crell** [comment]
Erf.  I forget exactly why I did it that way.  The alternative is probably to drop the constant and use array_filter() to remove the empty strings.  Or just require 7.2, which I'm not completely against...

I think I lean toward just going 7.2 here; it's not like this is a mission critical library for anyone yet. :smile:  Care to send in a PR?  (Remember to update the CI files, too.)

**Comment by PabloKowalczyk** [comment]
I can provide PR, no problem. Could point which CI file you are referring to? I don't see any.

**Comment by Crell** [comment]
Ugh, duh, this lib doesn't have a Travis integration because there's no tests. :smile:   (I know, I know, bad me...)
